import { UserItem, CreateUserInput } from '../types/user.types';
import { ROLES, PERMISSIONS } from '@/utils/constants';

let MOCK_USERS: UserItem[] = [
  {
    id: 'usr-101',
    name: 'Arun Kumar',
    email: 'arun@forgeui.com',
    role: ROLES.SUPER_ADMIN,
    department: 'Engineering',
    location: 'Bangalore, IN',
    tier: 'ENTERPRISE',
    status: 'ACTIVE',
    twoFactorEnabled: true,
    lastLogin: '2 mins ago',
    ipAddress: '192.168.1.10',
    usageQuota: '85 GB / 100 GB',
    billingPlan: 'ANNUAL',
    riskScore: 2,
    permissions: Object.values(PERMISSIONS),
    createdAt: '2026-01-15T08:30:00Z',
  },
  {
    id: 'usr-102',
    name: 'Priya Sharma',
    email: 'priya@forgeui.com',
    role: ROLES.ADMIN,
    department: 'Product Design',
    location: 'Mumbai, IN',
    tier: 'ENTERPRISE',
    status: 'ACTIVE',
    twoFactorEnabled: true,
    lastLogin: '1 hour ago',
    ipAddress: '192.168.1.15',
    usageQuota: '42 GB / 50 GB',
    billingPlan: 'ANNUAL',
    riskScore: 5,
    permissions: [PERMISSIONS.USERS_READ, PERMISSIONS.USERS_CREATE, PERMISSIONS.REPORTS_READ],
    createdAt: '2026-02-01T10:15:00Z',
  },
  {
    id: 'usr-103',
    name: 'Ravi Verma',
    email: 'ravi@forgeui.com',
    role: ROLES.MANAGER,
    department: 'DevOps & Cloud',
    location: 'Chennai, IN',
    tier: 'PRO',
    status: 'ACTIVE',
    twoFactorEnabled: false,
    lastLogin: 'Yesterday',
    ipAddress: '192.168.1.20',
    usageQuota: '68 GB / 100 GB',
    billingPlan: 'MONTHLY',
    riskScore: 12,
    permissions: [PERMISSIONS.USERS_READ, PERMISSIONS.REPORTS_READ],
    createdAt: '2026-02-10T14:45:00Z',
  },
  {
    id: 'usr-104',
    name: 'Ananya Roy',
    email: 'ananya@forgeui.com',
    role: ROLES.USER,
    department: 'Marketing',
    location: 'Delhi, IN',
    tier: 'STARTER',
    status: 'PENDING',
    twoFactorEnabled: false,
    lastLogin: 'Never',
    ipAddress: '45.33.22.11',
    usageQuota: '5 GB / 25 GB',
    billingPlan: 'MONTHLY',
    riskScore: 18,
    permissions: [PERMISSIONS.REPORTS_READ],
    createdAt: '2026-02-18T11:20:00Z',
  },
  {
    id: 'usr-105',
    name: 'Karthik Raja',
    email: 'karthik@forgeui.com',
    role: ROLES.USER,
    department: 'Security & QA',
    location: 'Hyderabad, IN',
    tier: 'PRO',
    status: 'INACTIVE',
    twoFactorEnabled: true,
    lastLogin: '3 weeks ago',
    ipAddress: '10.0.0.45',
    usageQuota: '12 GB / 25 GB',
    billingPlan: 'ANNUAL',
    riskScore: 85,
    permissions: [],
    createdAt: '2026-02-22T09:00:00Z',
  },
  {
    id: 'usr-106',
    name: 'Deepak Nair',
    email: 'deepak@forgeui.com',
    role: ROLES.ADMIN,
    department: 'Infrastructure',
    location: 'Kochi, IN',
    tier: 'ENTERPRISE',
    status: 'ACTIVE',
    twoFactorEnabled: true,
    lastLogin: '15 mins ago',
    ipAddress: '172.16.0.5',
    usageQuota: '90 GB / 100 GB',
    billingPlan: 'ANNUAL',
    riskScore: 3,
    permissions: [PERMISSIONS.USERS_READ, PERMISSIONS.USERS_CREATE],
    createdAt: '2026-02-25T16:00:00Z',
  },
  {
    id: 'usr-107',
    name: 'Meera Deshmukh',
    email: 'meera@forgeui.com',
    role: ROLES.MANAGER,
    department: 'Customer Success',
    location: 'Pune, IN',
    tier: 'PRO',
    status: 'ACTIVE',
    twoFactorEnabled: true,
    lastLogin: '4 hours ago',
    ipAddress: '192.168.2.14',
    usageQuota: '34 GB / 50 GB',
    billingPlan: 'ANNUAL',
    riskScore: 4,
    permissions: [PERMISSIONS.USERS_READ, PERMISSIONS.REPORTS_READ],
    createdAt: '2026-02-26T09:30:00Z',
  },
  {
    id: 'usr-108',
    name: 'Siddharth Joshi',
    email: 'siddharth@forgeui.com',
    role: ROLES.USER,
    department: 'Data Analytics',
    location: 'Ahmedabad, IN',
    tier: 'STARTER',
    status: 'ACTIVE',
    twoFactorEnabled: false,
    lastLogin: '5 mins ago',
    ipAddress: '10.200.1.8',
    usageQuota: '18 GB / 25 GB',
    billingPlan: 'MONTHLY',
    riskScore: 8,
    permissions: [PERMISSIONS.REPORTS_READ],
    createdAt: '2026-02-26T14:10:00Z',
  },
  {
    id: 'usr-109',
    name: 'Kavita Menon',
    email: 'kavita@forgeui.com',
    role: ROLES.ADMIN,
    department: 'Finance & HR',
    location: 'Trivandrum, IN',
    tier: 'ENTERPRISE',
    status: 'ACTIVE',
    twoFactorEnabled: true,
    lastLogin: '30 mins ago',
    ipAddress: '192.168.5.22',
    usageQuota: '65 GB / 100 GB',
    billingPlan: 'ANNUAL',
    riskScore: 1,
    permissions: [PERMISSIONS.USERS_READ, PERMISSIONS.USERS_CREATE],
    createdAt: '2026-02-27T10:00:00Z',
  },
  {
    id: 'usr-110',
    name: 'Vikram Singh',
    email: 'vikram@forgeui.com',
    role: ROLES.USER,
    department: 'Sales & Revenue',
    location: 'Jaipur, IN',
    tier: 'PRO',
    status: 'PENDING',
    twoFactorEnabled: false,
    lastLogin: 'Never',
    ipAddress: '49.207.18.5',
    usageQuota: '2 GB / 50 GB',
    billingPlan: 'MONTHLY',
    riskScore: 14,
    permissions: [PERMISSIONS.REPORTS_READ],
    createdAt: '2026-02-27T15:20:00Z',
  },
  {
    id: 'usr-111',
    name: 'Neha Kapoor',
    email: 'neha@forgeui.com',
    role: ROLES.MANAGER,
    department: 'Product Growth',
    location: 'Chandigarh, IN',
    tier: 'PRO',
    status: 'ACTIVE',
    twoFactorEnabled: true,
    lastLogin: 'Just now',
    ipAddress: '192.168.1.88',
    usageQuota: '48 GB / 50 GB',
    billingPlan: 'ANNUAL',
    riskScore: 3,
    permissions: [PERMISSIONS.USERS_READ, PERMISSIONS.REPORTS_READ],
    createdAt: '2026-02-28T08:00:00Z',
  },
  {
    id: 'usr-112',
    name: 'Rohan Patel',
    email: 'rohan@forgeui.com',
    role: ROLES.USER,
    department: 'Technical Support',
    location: 'Surat, IN',
    tier: 'STARTER',
    status: 'INACTIVE',
    twoFactorEnabled: false,
    lastLogin: '2 months ago',
    ipAddress: '117.240.1.99',
    usageQuota: '20 GB / 25 GB',
    billingPlan: 'MONTHLY',
    riskScore: 60,
    permissions: [],
    createdAt: '2026-02-28T10:45:00Z',
  },
];

export const usersApi = {
  getUsers: async (): Promise<UserItem[]> => {
    await new Promise((resolve) => setTimeout(resolve, 300));
    return [...MOCK_USERS];
  },

  createUser: async (input: CreateUserInput): Promise<UserItem> => {
    await new Promise((resolve) => setTimeout(resolve, 400));
    const newUser: UserItem = {
      id: `usr-${Date.now()}`,
      ...input,
      department: 'General Operations',
      location: 'Remote',
      tier: 'STARTER',
      twoFactorEnabled: false,
      lastLogin: 'Just now',
      ipAddress: '127.0.0.1',
      usageQuota: '1 GB / 25 GB',
      billingPlan: 'MONTHLY',
      riskScore: 0,
      permissions: [PERMISSIONS.USERS_READ],
      createdAt: new Date().toISOString(),
    };
    MOCK_USERS = [newUser, ...MOCK_USERS];
    return newUser;
  },

  deleteUser: async (id: string): Promise<void> => {
    await new Promise((resolve) => setTimeout(resolve, 300));
    MOCK_USERS = MOCK_USERS.filter((u) => u.id !== id);
  },
};
